version: '3.8'

services:
  bugbounty-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_APP: app.py
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
